/* Copyright (c) 2026 Nohuto */
(function attachPseudocodeDiffSource(global) {
  'use strict';

  const SETTINGS_KEY = 'nv-diff-pseudocode-settings-v1';
  const DEFAULT_LEFT_RELEASE = '11-23H2';
  const DEFAULT_RIGHT_RELEASE = '11-24H2';
  const DEFAULT_MODULE = 'ntoskrnl';
  const source = global.createNVDiffManifestSource({
    repository: 'nohuto/decompiled-pseudocode',
    dataset: 'decompiled-pseudocode',
    cacheKey: 'nv-diff-pseudocode-name-cache-v1'
  });

  const normalizationDefaults = () => ({
    stripCrossReferenceMetadata: true,
    normalizeRelocationSymbols: true,
    stripStorageLocationComments: true,
    normalizeDecompilerIdentifiers: true,
    normalizeNumericNotation: true,
    normalizeGeneratedLabels: false,
    normalizePrototypeExpansionArgs: false,
    trimTrailingWhitespace: true,
    ...(global.Normalization?.DEFAULTS || {})
  });

  const storageGet = (key, fallback) => {
    try {
      return localStorage.getItem(key) || fallback;
    } catch {
      return fallback;
    }
  };

  const storageSet = (key, value) => {
    try {
      localStorage.setItem(key, value);
    } catch {
    }
  };

  const readSettings = () => {
    const normalize = candidate => {
      const defaults = normalizationDefaults();
      const result = { ...defaults };
      Object.keys(defaults).forEach(key => {
        if (candidate?.[key] !== undefined) result[key] = Boolean(candidate[key]);
      });
      return result;
    };

    try {
      const parsed = JSON.parse(storageGet(SETTINGS_KEY, ''));
      return {
        normalization: normalize(parsed?.normalization),
        showFullFunction: parsed?.showFullFunction !== undefined ? Boolean(parsed.showFullFunction) : true
      };
    } catch {
      return { normalization: normalizationDefaults(), showFullFunction: true };
    }
  };

  const writeSettings = settings => {
    storageSet(SETTINGS_KEY, JSON.stringify({
      normalization: settings.normalization,
      showFullFunction: Boolean(settings.showFullFunction)
    }));
  };

  const resetSettings = () => {
    const settings = { normalization: normalizationDefaults(), showFullFunction: true };
    writeSettings(settings);
    return settings;
  };

  const addSetting = (body, id, label, checked) => {
    const row = document.createElement('label');
    row.className = 'bindiff-setting-row';
    row.htmlFor = id;
    row.innerHTML = `<input id="${id}" type="checkbox"><span>${label}</span>`;
    const input = row.querySelector('input');
    input.checked = checked;
    body.appendChild(row);
    return input;
  };

  const renderSettings = (body, onChange) => {
    const settings = readSettings();
    body.replaceChildren();
    const inputs = {
      stripCrossReferenceMetadata: addSetting(body, 'diff-setting-strip-cross-reference-metadata', 'Hide XREF comments', settings.normalization.stripCrossReferenceMetadata),
      normalizeRelocationSymbols: addSetting(body, 'diff-setting-normalize-relocation-symbols', 'Hide build specific addresses/symbols', settings.normalization.normalizeRelocationSymbols),
      stripStorageLocationComments: addSetting(body, 'diff-setting-strip-storage-location-comments', 'Hide register/stack comments', settings.normalization.stripStorageLocationComments),
      normalizeDecompilerIdentifiers: addSetting(body, 'diff-setting-normalize-decompiler-identifiers', 'Normalize autogenerated variable/argument names', settings.normalization.normalizeDecompilerIdentifiers),
      normalizeNumericNotation: addSetting(body, 'diff-setting-normalize-numeric', 'Treat equivalent numbers as same (hex/dec/suffix)', settings.normalization.normalizeNumericNotation),
      normalizeGeneratedLabels: addSetting(body, 'diff-setting-normalize-labels', 'Ignore generated label number changes', settings.normalization.normalizeGeneratedLabels),
      normalizePrototypeExpansionArgs: addSetting(body, 'diff-setting-normalize-prototype', 'Ignore extra trailing default arguments', settings.normalization.normalizePrototypeExpansionArgs),
      showFullFunction: addSetting(body, 'diff-setting-show-full', 'Show full function', settings.showFullFunction),
      trimTrailingWhitespace: addSetting(body, 'diff-setting-trim-whitespace', 'Ignore whitespace only changes', settings.normalization.trimTrailingWhitespace)
    };

    const sync = () => {
      writeSettings({
        normalization: {
          stripCrossReferenceMetadata: inputs.stripCrossReferenceMetadata.checked,
          normalizeRelocationSymbols: inputs.normalizeRelocationSymbols.checked,
          stripStorageLocationComments: inputs.stripStorageLocationComments.checked,
          normalizeDecompilerIdentifiers: inputs.normalizeDecompilerIdentifiers.checked,
          normalizeNumericNotation: inputs.normalizeNumericNotation.checked,
          normalizeGeneratedLabels: inputs.normalizeGeneratedLabels.checked,
          normalizePrototypeExpansionArgs: inputs.normalizePrototypeExpansionArgs.checked,
          trimTrailingWhitespace: inputs.trimTrailingWhitespace.checked
        },
        showFullFunction: inputs.showFullFunction.checked
      });
      onChange();
    };
    Object.values(inputs).forEach(input => input.addEventListener('change', sync));
  };

  const normalizeText = source => String(source || '').replace(/\r\n?/g, '\n');

  const preparePair = (leftSource, rightSource) => {
    const settings = readSettings();
    const result = global.Normalization?.preparePair
      ? global.Normalization.preparePair(leftSource, rightSource, settings.normalization)
      : { leftText: normalizeText(leftSource), rightText: normalizeText(rightSource), equivalent: false };
    const fullContext = Math.max(result.leftText.split('\n').length, result.rightText.split('\n').length) + 2;
    return {
      leftText: result.leftText,
      rightText: result.rightText,
      equivalent: Boolean(result.equivalent),
      context: settings.showFullFunction ? fullContext : 4
    };
  };

  const prepareSingle = source => {
    const settings = readSettings();
    return global.Normalization?.normalize
      ? global.Normalization.normalize(source, settings.normalization).text
      : normalizeText(source);
  };

  global.NVDiffSources = global.NVDiffSources || {};
  global.NVDiffSources.pseudocode = {
    ...source,
    defaultLeft: DEFAULT_LEFT_RELEASE,
    defaultRight: DEFAULT_RIGHT_RELEASE,
    defaultModule: DEFAULT_MODULE,
    extraScripts: ['main/min/normalization.min.js'],
    preparePair,
    prepareSingle,
    renderSettings,
    resetSettings,
    highlightBlockComments: true
  };
})(window);
